version: '3.8'

services:
  # Redis 
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    restart: always

  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
    restart: always

  # PostgreSQL 
  postgres:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-container
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword!
    restart: always